version: '3.1'
services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        volumes:
            - ${HOST_DOCKER}:/var/run/docker.sock
            - ${HOST_JENKINS_DATA}:/var/jenkins_home
        ports:
            - 8080:8080
            - 50000:50000
    nginx:
       image: nginx:latest
       container_name: nginx
       volumes:
         - ${NGINX_CONF}/nginx.conf:/etc/nginx/nginx.conf
       ports:
         - 80:80
         - 8080:8080
         - 443:443